import {
	SIZE_HEADER,
	FAMILY_HEADER,
	PROVIDER_HEADER,
	DATE_HEADER,
	QUANTITY_HEADER,
	DESCRIPTION_HEADER,
	SKU_HEADER,
} from "../../helper/header_constants";

export const SUBMISSION_TYPES = ["Compras", "Producción"];

export const HEADER_VALUES = {
	[SUBMISSION_TYPES[0]]: [
		SIZE_HEADER,
		PROVIDER_HEADER,
		DATE_HEADER,
		QUANTITY_HEADER,
	],
	[SUBMISSION_TYPES[1]]: [
		SIZE_HEADER,
		FAMILY_HEADER,
		SKU_HEADER,
		DESCRIPTION_HEADER,
		DATE_HEADER,
		QUANTITY_HEADER,
	],
};

export const POST_HEADERS = {
	[SUBMISSION_TYPES[0]]: [
		SIZE_HEADER,
		QUANTITY_HEADER,
		PROVIDER_HEADER,
		DATE_HEADER,
	],
	[SUBMISSION_TYPES[1]]: [SKU_HEADER, DATE_HEADER, QUANTITY_HEADER],
};

export const POST_PATH = {
	[SUBMISSION_TYPES[0]]: "/compras",
	[SUBMISSION_TYPES[1]]: "/plan_de_produccion",
};
