export const SIZE_HEADER = "Tamaño";
export const FAMILY_HEADER = "Familia";
export const SKU_HEADER = "SKU";
export const DESCRIPTION_HEADER = "Descripción";
export const DATE_HEADER = "Fecha";
export const QUANTITY_HEADER = "Cantidad";
export const PROVIDER_HEADER = "Proveedor";

const BACKEND_HEADERS = {
	SIZE: "tamano",
	ID_SIZE: "id_tamano",
	FAMILY: "familia",
	ID_FAMILY: "id_familia",
	SKU: "sku",
	DESCRIPTION: "descripcion",
	PROVEEDOR: "proveedor",
	DATE: "fecha",
	QUANTITY: "cantidad",
};

export const HEADER_CONVERSION = {
	[BACKEND_HEADERS.SIZE]: SIZE_HEADER,
	[BACKEND_HEADERS.FAMILY]: FAMILY_HEADER,
	[BACKEND_HEADERS.SKU]: SKU_HEADER,
	[BACKEND_HEADERS.DESCRIPTION]: DESCRIPTION_HEADER,
	[BACKEND_HEADERS.PROVEEDOR]: PROVIDER_HEADER,
	[BACKEND_HEADERS.DATE]: DATE_HEADER,
	[BACKEND_HEADERS.QUANTITY]: QUANTITY_HEADER,
};

export const HEADER_CONVERSION_TO_REQUEST: Record<string, string> = {
	[FAMILY_HEADER]: BACKEND_HEADERS.ID_FAMILY,
	[SIZE_HEADER]: BACKEND_HEADERS.ID_SIZE,
	[SKU_HEADER]: BACKEND_HEADERS.SKU,
	[DESCRIPTION_HEADER]: BACKEND_HEADERS.DESCRIPTION,
	[QUANTITY_HEADER]: BACKEND_HEADERS.QUANTITY,
	[DATE_HEADER]: BACKEND_HEADERS.DATE,
	[PROVIDER_HEADER]: BACKEND_HEADERS.PROVEEDOR,
};

export const HEADER_WITH_NUMERIC_VALUES = [SKU_HEADER, QUANTITY_HEADER];
